INSERT INTO cf_product (name,description,url_repository,login_repository,password_repository) VALUES ( 'ceres', 'SISTEMA CERES','https://lordjackson@bitbucket.org/jacklan/ceres.git','lordjackson@gmail.com', '987456');
INSERT INTO cf_group_menu (name) VALUES ('CADASTRO');
INSERT INTO cf_group_menu (name) VALUES ('RELATÓRIO');
INSERT INTO cf_group_menu (name) VALUES ('GRÁFICO');
INSERT INTO cf_group_menu (name) VALUES ('ACOMPANHAMENTO');
INSERT INTO cf_module (product_id,name,title) VALUES ('1','SRH','SISTEMA DE GERENCIAMENTO DE RECURSOS HUMANOS');
INSERT INTO cf_module (product_id,name,title) VALUES ('1','PONTO','PONTO ELETRONICO');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Servidor*','servidor','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('1','Servidor List','ServidorList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('1','Servidor Form','ServidorForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('1','Meu Perfil','MeuPerfilList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('1','Servidor Foto','ServidorFormFoto');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('1','Servidor Foto Perfil','ServidorFormFotoPerfil');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('1','Servidor Form Consulta','ServidorFormConsulta');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Lotacao*','lotacao','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('2','Lotação Detalhe','ServidorLotacaoDetalhe');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('2','Lotação Detalhe Consulta','ServidorLotacaoDetalheConsulta');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('2','UnidadeServidorDetalhe','UnidadeServidorDetalhe');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Tipo Regime','tipo_regime','MANDATORY','1');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Cadastro Base*','cadbase','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Área de Conhecimento','AreaConhecimentoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Cargo Form','CargoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Cargo','CargoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Conselho de Classe','ConselhoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Funcao Form','FuncaoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Função','FuncaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Instituicao Ensino Form','InstituicaoEnsinoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Instituição de Ensino','InstituicaoEnsinoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Motivo Afastamento','MotivoAfastamentoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Motivo Concessão','MotivoConcessaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Motivo Suspensão','MotivosuspensaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Município','MunicipioList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Nível Remuneratorio','NivelSalarialList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Orgão','OrgaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Ramais','RamalList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Requisito Cargo','RequisitoCargoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor','SetorList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor Grupo','SetorGrupoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Tipo Licença','TipoLicencaList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Tipo Solicitação','TipoSolicitacaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Titulação','FormacaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Unidade Operativa','UnidadeOperativaList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','CargoServidorDetalhe','CargoServidorDetalhe');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Conselho List','ConselhoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Conselho Form','ConselhoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Municipio Form','MunicipioForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Municipio List','Municipio List');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','NivelSalarial Form','NivelSalarialForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Nivel Salarial List','NivelSalarialList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Orgao Form','OrgaoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Orgao List','OrgaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Ramal Form','RamalForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Ramal List','RamalList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Servidor Consulta List','ServidorConsultaList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Unidade Operativa Form','UnidadeOperativaForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Unidade Operativa Form Foto','UnidadeOperativaFormFoto');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Unidade Operativa List','UnidadeOperativaList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor Form','SetorForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor List','SetorList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor Grupo Detalhe','SetorGrupoDetalhe');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor Grupo Form','SetorGrupoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor Grupo List','SetorGrupoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('4','Setor Grupo Report','SetorGrupoReport');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Relatório*','relservidor','MANDATORY','2');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Servidor Personalizado*','relservidor','MANDATORY','2');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('6','Servidor Personalizado','GeraRelatorioPersonalizadoServidorList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('6','RelatorioPersonalizadoServidorPDF','RelatorioPersonalizadoServidorPDF');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('6','RelatorioListaServidoresExcel','RelatorioListaServidoresExcel');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Gráfico*','grafico','MANDATORY','3');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('1','Quantitativo Servidor*','graf_qtd_servidor','MANDATORY','3');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('8','Servidores QTD','GeraGraficoQtdServidorList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('8','ServidorporRegionalGraf','ServidorporRegionalGraf');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('8','Grafico Qtd Servidor por Cargo List','GeraGraficoQtdServidorporCargoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('8','Grafico Dimensionamento Servidor List','GeraGraficoDimensionamentoServidorList');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Bater Ponto*','batida','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('9','Bater Ponto','MarcacaoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('9','Marcacao Form','MarcacaoForm');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Cadastro Base*','cadbase','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('10','Horário Espécial List','HorarioEspecialList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('10','Horário Espécial Form','HorarioEspecialForm');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Feriados*','feriados','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('11','Feriados','FeriadosList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('11','Feriados Form','FeriadosForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('11','Feriados List','FeriadosList');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Tipo Justificativa*','tipo_justificativa','MANDATORY','1');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('12','Tipo Justificativa List','TipoJustificativaPontoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('12','TipoJustificativa Ponto Form','TipoJustificativaPontoForm');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Relatório*','relescalajornada','MANDATORY','2');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Batidas por Servidor*','batidas_por_servidor','MANDATORY','2');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('14','Marcacao Relogio Detalhe','MarcacaoRelogioDetalhe');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('14','Marcacao Relogio Servidor Detalhe','MarcacaoRelogioServidorDetalhe');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('14','Marcacao Servidor List','MarcacaoServidorList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('14','RelatorioBatidasPontoServidorPDF','RelatorioBatidasPontoServidorPDF');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('14','Documento Justificativa PDF','RelatorioDocumentoJustificativaPDF');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Servidor sem Batidas*','servidor_sem_batidas','MANDATORY','2');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Acompanhamento*','acompanhamento','MANDATORY','5');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('16','Log Banco Horas List','LogBancoHorasList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('16','Log Marcacao List','LogMarcacaoList');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Justificativa*','justificativa','MANDATORY','5');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Acompanhamento List','JustificativaPontoAcompanhamentoList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Chefe Form','JustificativaPontoChefeForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Chefe Geral','JustificativaPontoChefeGeral');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Chefe Geral Form','JustificativaPontoChefeGeralForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Chefe List','JustificativaPontoChefeList');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Filtro Chefe','JustificativaPontoFiltroChefe');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','Justificativa Ponto Form','JustificativaPontoForm');
INSERT INTO cf_feature_page (feature_id,name,controller) VALUES ('17','JustificativaPontoList','JustificativaPontoList');
INSERT INTO cf_feature (module_id,title,name,type,group_menu_id) VALUES ('2','Abonar*','abonar','MANDATORY','5');
